name: Build & Publich Container

on:
  push:
    tags:
      - '*'

jobs:

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set output
  #       id: vars
  #       run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
  #     - name: Check output
  #       env:
  #         RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
  #       run: |
  #         echo $RELEASE_VERSION
  #         echo ${{ steps.vars.outputs.tag }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        id: get_tag
        run: echo ::set-output name=NAME::${GITHUB_REF#refs/tags/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cache
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ashurpin/odyssey:${{ steps.get_tag.outputs.NAME }}
          build-args:
            - ODYSSEY_VERSION: ${{ steps.get_tag.outputs.NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
